trigger:
  - master

pool: Default

stages:
  - stage: Build
    jobs:
      - job: Compile
        steps:
          - script: echo "Hello World"
      - job: RunUnittest
        steps:
          - script: date
          - script: echo "Running Unit Test cases"

  - stage: Inspection
    jobs:
      - job: sonarqube
        steps:
          - script: echo "Code Inspection Started"
          - script: /opt/sonarqube/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner

  - stage: publish
    jobs:
      - job: publish
        displayName: Docker build and publish
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "myacr"
              repository: "pythonapp"
              command: "build"
              Dockerfile: "**/Dockerfile"
