apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
  labels:
    app: java-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: hello-world-java
        image: adodemo12.azurecr.io/javawebapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-java-service
spec:
  selector:
    app: java-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer