apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
  labels:
    app: python-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: hello-world-python
        image: adodemo12.azurecr.io/pythonapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service
spec:
  selector:
    app: python-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer